name: Android Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [debug, release]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential make
    
    - name: Set up Android build environment
      run: |
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/27.3.13750724
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
    
    - name: Initialize Android build
      run: |
        cd src/misc/android
        make init
    
    - name: Build Android APK
      run: |
        cd src/misc/android
        make apk
    
    - name: Sign APK (for testing)
      run: |
        cd src/misc/android
        make signed
    
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: opensurge-android-${{ matrix.build-type }}
        path: src/misc/android/build/*.apk
        retention-days: 30
    
    - name: Upload debug info
      if: matrix.build-type == 'debug'
      uses: actions/upload-artifact@v4
      with:
        name: opensurge-android-debug-info
        path: src/misc/android/build/
        retention-days: 30