name: Documentation

on:
  push:
    branches: [ master, main ]
    paths:
      - 'README.md'
      - 'docs/**'
      - 'scripts/**'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'README.md'
      - 'docs/**'
      - 'scripts/**'

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install -g jsdoc
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz
    
    - name: Generate API documentation
      run: |
        # Generate documentation from source code comments
        if [ -d "src" ]; then
          doxygen -g Doxyfile
          doxygen Doxyfile
        fi
    
    - name: Generate SurgeScript documentation
      run: |
        # Create documentation for SurgeScript files
        mkdir -p docs/scripts
        find scripts -name "*.ss" -exec echo "Documenting {}" \;
        
        # Create a simple index of all scripts
        echo "# SurgeScript Files" > docs/scripts/README.md
        echo "" >> docs/scripts/README.md
        find scripts -name "*.ss" | sort >> docs/scripts/README.md
    
    - name: Validate documentation
      run: |
        # Check if documentation files are valid
        if [ -f "README.md" ]; then
          echo "README.md exists and is valid"
        fi
        
        # Check for broken links in markdown files
        find . -name "*.md" -exec echo "Checking {}" \;
    
    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: |
          docs/
          html/
        retention-days: 30

  spell-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install aspell
      run: sudo apt-get update && sudo apt-get install -y aspell aspell-en
    
    - name: Spell check documentation
      run: |
        # Check spelling in markdown files
        for file in $(find . -name "*.md" -not -path "./.git/*"); do
          echo "Checking spelling in $file"
          aspell check --mode=markdown "$file" || true
        done
